### ISSUE TITLE
有个节点插件里面运行的服务获取不到端口号

### ISSUE THREAD

**Issue by xa-yifan** [dromara/Jpom#14]
![image](https://user-images.githubusercontent.com/61110064/168783637-f8d6182b-f255-4b40-89f9-e57e0fc84ab1.png)

**Comment by xa-yifan** [comment]
其他节点可以
如：
![image](https://user-images.githubusercontent.com/61110064/168784210-ac858741-12f3-4ee3-9555-74ca93a5f320.png)

**Comment by bwcx-jzy** [comment]
这个监控获取到的端口号，仅供参考。

具体实现使用命令解析结果
```
netstat -antup | grep pidxxx |grep "LISTEN" | head -20
```
能否获取到需要看对应项目是否有端口并且满足条件

**Comment by xa-yifan** [comment]
可以了原来是没安装net-tools网络工具，导致netstat命令找不到
