### ISSUE TITLE
自定义项目访问接口探活

### ISSUE THREAD

**Issue by dylan-tao** [dromara/Jpom#2]
期望不仅仅是固定的监控方式，可以做到自定义多个接口探活。并且可以配合Nginx自动摘流量，在发布的时候先在Nginx上修改指定发布机器的权重为0，在服务启动后并且探活基本自定义接口ok，将权重挂回🙏

**Comment by jiangzeyin** [comment]
好的，我们这边会根据情况跟进

**Comment by youtao531** [comment]
还有SpringCloud Nacos，是否考虑发布前先将服务实例禁用或权重调整为0等待没有流量进入实例在重启？

**Comment by jiangzeyin** [comment]
> 

这块后期看看配合接口探活，实现 nginx 切换负载

**Comment by jiangzeyin** [comment]
> 还有SpringCloud Nacos，是否考虑发布前先将服务实例禁用或权重调整为0等待没有流量进入实例在重启？

**Comment by jiangzeyin** [comment]
> 还有SpringCloud Nacos，是否考虑发布前先将服务实例禁用或权重调整为0等待没有流量进入实例在重启？

这块后期看看配合接口探活，实现 nginx 切换负载

**Comment by bwcx-jzy** [comment]
jpom 新增 DSL 项目模式，DSL 模式可以实现自定义接口探活：参考实践案例 https://jpom.top/pages/610387/
