### ISSUE TITLE
权限控制按钮的显示

### ISSUE THREAD

**Issue by ddddl-cn** [dromara/Jpom#29]
权限控制按钮的显示
权限树

**Comment by bwcx-jzy** [comment]
请查看文档 https://jpom.top/pages/ca90a5/#%E6%9D%83%E9%99%90%E8%AF%B4%E6%98%8E

**Comment by ddddl-cn** [comment]
我的意思是，把修改权限关了之后，相关的按钮也没有了

**Comment by bwcx-jzy** [comment]
暂时不考虑实现
