### ISSUE TITLE
jpom-2.10.11   Service.sh 问题

### ISSUE THREAD

**Issue by ufoxu** [dromara/Jpom#31]
binAbsName   JAVA_HOME  CLASSPATH 应该是否定判断
function install() {

    if [ -f "$serviceFile" ]; then
        echo "service file already exists" 2>&2
        exit 2
    fi
    if [ ! -f "$binAbsName" ]; then
        echo "$binAbsName not found" 2>&2
        exit 2
    fi
    if [ ! -z "$JAVA_HOME" ]; then
        echo "JAVA_HOME variable not found" 2>&2
        exit 2
    fi
    if [ ! -z "$CLASSPATH" ]; then
        echo "CLASSPATH variable not found" 2>&2
        exit 2
    fi

**Comment by bwcx-jzy** [comment]
是需要判断的，因为对应的变量会配置到服务中，这样服务才能使用到对应的 java 环境

**Comment by bwcx-jzy** [comment]
如果出现无法正常安装服务需要安装截图修改一下脚本 ![fec04c2af25c6c580d7265beb857870](https://user-images.githubusercontent.com/16408873/215691934-f42926fc-90d8-4b20-b3ed-85a6be8929ec.png)
