### ISSUE TITLE
建议加个在线demo，这样就不用自己亲自安装一遍，来看是否符合自己需求了

### ISSUE THREAD

**Issue by czxin788** [dromara/Jpom#35]
建议加个在线demo，这样就不用自己亲自安装一遍，来看是否符合自己需求了

**Comment by bwcx-jzy** [comment]
前期搭建过演示系统，后期考虑成本原因取消了，Jpom 本身为开源项目没有收入的情况维护一个演示系统服务器不太划算

**Comment by bwcx-jzy** [comment]
Jpom 目前文档涉及的方面用不同场景还是很充足，建议按照文档来搭建一个走一遍流程即可。搭建基本 5~10 分钟即可完成
