### ISSUE TITLE
使用微软的DevOps作为代码仓库，新增仓库时提示账号密码错误

### ISSUE THREAD

**Issue by cheakin** [dromara/Jpom#43]
如题，使用微软的DevOps作为代码仓库，平常我是使用IDEA中的git直接拉取，输入账号密码后就可以拉取成功了；但在Jpom中，新增仓库时提示账号密码错误。
另外，因为我的仓库没有SSL证书，所以一般是要关闭git的SSL校验的，不知道和这个有没有关系。

我确定我的账号密码是没有错误的

**Comment by bwcx-jzy** [comment]
提示的错误信息截图看看

**Comment by cheakin** [comment]
![image](https://user-images.githubusercontent.com/29295460/230259838-4d28306d-9b86-4c8c-a17f-ef7decdcd28c.png)

![image](https://user-images.githubusercontent.com/29295460/230259790-be66ee1c-407b-425b-b4eb-71102e24ff9b.png)

**Comment by bwcx-jzy** [comment]
![image](https://user-images.githubusercontent.com/16408873/230261291-904e1bfd-4e89-44d8-a2ef-497902b3d7b1.png)
根据异常信息大概率是账号方面的问题，需要你自己仔细排查

**Comment by cheakin** [comment]
我试了我同事的账号，也不行，可能和仓库类型有关把。我再看看
