### ISSUE TITLE
容器构建什么时候添加其他基础镜像。

### ISSUE THREAD

**Issue by small-ora** [dromara/Jpom#46]
开发大佬好，请问容器构建大概计划什么时候支持其他基础镜像，或者添加多阶段构建的功能，直接一步打包出docker镜像，然后推送到镜像仓库。

**Comment by bwcx-jzy** [comment]
![image](https://github.com/dromara/Jpom/assets/16408873/382d2432-5362-469e-8f60-9a4d13a20c9f)
已经支持了
