### ISSUE TITLE
【项目管理->在线构建->仓库信息】使用令牌时数据库字段长度不够

### ISSUE THREAD

**Issue by cheakin** [dromara/Jpom#47]
如图，在使用github新版令牌时，选择项目添加后报错
![image](https://github.com/dromara/Jpom/assets/29295460/7b6199d2-3414-46b6-88e4-4bb649df9563)

**Comment by bwcx-jzy** [comment]
beta 版已经解决，可以开启 beta 计划更新。正式版还需要等待后续发版
