### ISSUE TITLE
nginx list loading status is not over

### ISSUE THREAD

**Issue by onlyonezhongjinhui** [dromara/Jpom#5]
![image](https://user-images.githubusercontent.com/19932240/112916178-9d658300-9132-11eb-8798-97cd4d2d71db.png)

**Comment by Bacchusgift** [comment]
这个问题是由于前端没有拿到nginx的配置目录导致的，是一个前端交互的bug。
你先在白名单目录里添加一个nginx的白名单目录就可以解决此问题

**Comment by xzblog** [comment]
问题已修复： [提交记录](https://github.com/dromara/Jpom/commit/d5fa99e7250c10e9a24519c77d6e67642f224aa6)
