### ISSUE TITLE
project list loading status is not over

### ISSUE THREAD

**Issue by onlyonezhongjinhui** [dromara/Jpom#6]
![image](https://user-images.githubusercontent.com/19932240/112916921-1fa27700-9134-11eb-8c9b-52e662630cc8.png)

**Comment by Idiot-Alex** [comment]
What is the version of Jpom used?
And are there any error messages?

**Comment by jiangzeyin** [comment]
这个问题其实算一个没有优化的交互问题，因为这个目录不存在文件。前端ui这边没有获取到数据，并没有取消loading

**Comment by jiangzeyin** [comment]
已经修护 2.5.1
