### ISSUE TITLE
Agent.sh脚本的问题

### ISSUE THREAD

**Issue by yusiwen** [dromara/Jpom#64]
由这个[commit](https://github.com/dromara/Jpom/commit/3e1aa535ddddefd7386d48fa88e15773c3966ab7)带来的问题
`modules/agent/src/main/bin/Agent.sh`中`errorExit`没有定义

**Comment by bwcx-jzy** [comment]
```
function errorExit() {
	echo "$1" 2>&2
	if [ "${mode}" == "-s" ]; then
		logStdout "$1"
	fi
	exit 1
}
```

**Comment by bwcx-jzy** [comment]
新版本已经发版
