### ISSUE TITLE
启动脚本Server.sh在Mac机器上存在错误

### ISSUE THREAD

**Issue by zhangyijun** [dromara/Jpom#68]
包括Agent.sh也有类似问题

JPOM_SERVER_APPLICATION
automatic running：server-2.10.45.jar
Jpom server starting:46075
tail: illegal option -- -
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]

**Comment by bwcx-jzy** [comment]
脚本目前未对 mac 适配
