### ISSUE TITLE
终端命令黑名单可绕过

### ISSUE THREAD

**Issue by KeekLove** [dromara/Jpom#69]
您好:
   我发现目前的终端命令黑名单是可以通过tap或者光标移动来破坏最终命令绕过的，目前我发现仅仅针对backspace做了处理
![image](https://github.com/dromara/Jpom/assets/46373026/658594d2-21d5-4deb-b782-299c3e61c68b)
所以我觉得如果没有其他的方式的话，仅仅从连接的io内容检测的话去实现的终端命令黑名单和终端日志记录这两个功能是不合理，要么就只能从linux虚拟机本身做处理了

**Comment by bwcx-jzy** [comment]
此功能定位还是一个轻量化功能，如果您有更好的解决方案欢迎贡献

**Comment by KeekLove** [comment]
了解了，谢谢解答
