### ISSUE TITLE
程序重启有问题

### ISSUE THREAD

**Issue by tianbo-0319** [dromara/Jpom#74]
<img width="500" alt="image" src="https://github.com/dromara/Jpom/assets/40235929/789a0cb0-92e1-4c6c-b31d-4a82b9b65966">

**Comment by tianbo-0319** [comment]
没反应了，stop,restart都这样

**Comment by bwcx-jzy** [comment]
需要等待进程正常关闭

**Comment by bwcx-jzy** [comment]
默认是 kill -15,bash /xxxx/Server.sh restart -15

你可以使用 kill -9 ,bash /xxxx/Server.sh restart -9 来强制关闭，但是容易出现数据丢失，h2 数据库损坏情况

**Comment by tianbo-0319** [comment]
好的，可以了，🙏
