### ISSUE TITLE
节点&项目里的项目管理具体是怎么使用的

### ISSUE THREAD

**Issue by tianbo-0319** [dromara/Jpom#75]
节点&项目里的项目管理具体是怎么使用的？
我建了一个java项目
<img width="768" alt="image" src="https://github.com/dromara/Jpom/assets/40235929/c16ea3e8-61e0-469e-b8b5-7359c7de9338">
点击控制台
<img width="194" alt="image" src="https://github.com/dromara/Jpom/assets/40235929/fcb0fc47-8108-487c-b9bd-72bb8f5ae6ae">
然后就在不停的执行脚本。。。我这个脚本是打包运行docker的

**Comment by bwcx-jzy** [comment]
https://jpom.top
