### ISSUE TITLE
钉钉扫码登录

### ISSUE THREAD

**Issue by Cuiys1458** [dromara/Jpom#76]
钉钉扫码登录创建员工为中文名，无权限 ，无空间，编辑后提示登录名格式不正确（英文字母 、数字和下划线）,并且长度必须3-50

**Comment by bwcx-jzy** [comment]
后面版本已经优化识别第三方用户等待发版即可（先发 beta）

**Comment by Cuiys1458** [comment]
我看文档中有飞书，和gitlab 相关的认证方案文档，顺便想问下 是后面会出相应的版本么

**Comment by Cuiys1458** [comment]
好的感谢

**Comment by bwcx-jzy** [comment]
![image](https://github.com/dromara/Jpom/assets/16408873/92779453-b0fb-4b62-ba0e-b7299bdf4e0f)

**Comment by bwcx-jzy** [comment]
再积累一些优化才发版

**Comment by Cuiys1458** [comment]
感谢采纳需求，这个也是我

**Comment by fyjc-wlj** [comment]
2.11.4.0 已经发版
