### ISSUE TITLE
按照官网的示例配置Nginx后，项目启动报错

### ISSUE THREAD

**Issue by cheakin** [dromara/Jpom#78]
报错信息如图：
![image](https://github.com/dromara/Jpom/assets/29295460/a6c282b3-763d-4d47-9016-cba94c04f8dc)
报错信息：
Unable to make field private final int java.lang.ProcessImpl.pid accessible: module java.base does not "opens java.lang" to unnamed module @52d455b8

**Comment by fyjc-wlj** [comment]
文档有相关说明，请看文档
