### ISSUE TITLE
ssh node cannot be created

### ISSUE THREAD

**Issue by onlyonezhongjinhui** [dromara/Jpom#8]
![image](https://user-images.githubusercontent.com/19932240/112918671-fbe13000-9137-11eb-81c6-0ec6d391277a.png)

**Comment by jiangzeyin** [comment]
@Idiot-Alex  这块很可能是全局网络错误，或者ssh新不正确然后引起的

**Comment by jiangzeyin** [comment]
也有可能是添加的 ssh信息不正确，然后引起接口超时了
