### ISSUE TITLE
是否考虑支持项目构建后发布到多个服务器

### ISSUE THREAD

**Issue by wangeDear** [dromara/Jpom#82]
当前很多应用都是分布式的，一次构建需要发布到多个服务器启动多实例，对于多实例部署的场景是否支持呢

**Comment by bwcx-jzy** [comment]
节点分发

**Comment by wangeDear** [comment]
> 节点分发

了解，谢谢。

另还有个场景就是一个工程下面可能有几个微服务，那一次构建就可以了，然后对不同微服务进行分发部署，而不需要每次都要重新构建。

**Comment by bwcx-jzy** [comment]
目前一个构建是一个任务和一个发布，还不支持一个构建多个任务或者多个发布。不过已经有规划还不知道什么时候能开发完
