### ISSUE TITLE
can not select pulish

### ISSUE THREAD

**Issue by zoowayss** [dromara/Jpom#85]
<img width="1512" alt="image" src="https://github.com/dromara/Jpom/assets/78424515/1e4b9c74-009d-4b27-81c7-e4e10000d7fc">
why?

**Comment by zoowayss** [comment]
Details i used
git clone   git@github.com:dromara/Jpom.git
cd Jpom
docker compose up -d

**Comment by bwcx-jzy** [comment]
在构建流程的第二步未选择仓库的分支，此版本提升有错误。后续版本修正提升信息
