### ISSUE TITLE
这个地方为什么不使用预编译呢？可以有效的加快正则的匹配速度

### ISSUE THREAD

**Issue by ycr1997** [dromara/Jpom#9]
https://github.com/dromara/Jpom/blob/a1517c8d85cf2766dc993311e8d9896ee79a22f4/modules/agent/src/main/java/io/jpom/common/commander/AbstractTomcatCommander.java#L109

**Comment by jiangzeyin** [comment]
感谢反馈，已经更换方法。目前已经提交到 dev 分支，等待下次发版
