### ISSUE TITLE
Bug: 资产管理-SSH管理-终端日志列表内展示执行命令不完成

### ISSUE THREAD

**Issue by YazaiHu** [dromara/Jpom#91]
准备查看云主机内安装的docker版本，预期执行命令docker --version.

步骤：
1、打开终端按钮，输入doc三个字符以后按回车键补全，如下图
![jpom-1](https://github.com/user-attachments/assets/1b21beac-a616-46c4-bb9f-3022f98aea06)
![jpom-2](https://github.com/user-attachments/assets/c754b007-d2df-4b79-8958-9d83d7368a33)
![jpom-3](https://github.com/user-attachments/assets/e4236ec7-d137-4555-8743-846128f2a3c8)

2、打开终端日志，只显示doc三个字符，无法显示完整的docker命令。

猜测这个终端是根据键盘输入字符记录命令的，没有考虑到Linux下面按tab键可以补全Linux命令导致引起的。

**Comment by bwcx-jzy** [comment]
版本号提供一下

**Comment by bwcx-jzy** [comment]
2.11.9.2 beta 已经发版可以更新测试
