### ISSUE TITLE
jpom插件端管理服务的

### ISSUE THREAD

**Issue by zhangzongbin** [dromara/Jpom#92]
我在一个jpom插件端上部署了10个项目，当我发现重启jpom插件端服务的时候它会将管理的项目都会重启，并且会等待项目启动成功，请问一下作者，如果插件端挂了的话，会不会导致我所有在这个插件端部署的项目都会死掉呢，如果出现这种问题，作者是怎么考虑的呢

**Comment by bwcx-jzy** [comment]
正常使用是不会出现类似情况
