### ISSUE TITLE
项目Jar方式启动，如何自定义Java的路径（插件端）

### ISSUE THREAD

**Issue by donglex** [dromara/Jpom#93]
版本：2.11.9

在项目列表中新增一个项目，启动方式指定Jar包。如果没有在环境变量配置JDK，那么会提示 “当前服务器 jps 命令异常,请检查 jdk 是否完整,以及 java 环境变量是否配置正确”。

预期实现效果：
不配置环境变量前提下，在页面上能自定义JDK目录并且项目正常启动

**Comment by bwcx-jzy** [comment]
请参考文档排查并解决
