### ISSUE TITLE
java的jar项目分发（完整顺序执行(有执行失败将结束本次)）的时候无法监听到项目启动失败，从而停止分发，从而导致整个集群全部停机

### ISSUE THREAD

**Issue by zhaowenjie951214** [dromara/Jpom#98]
java的jar项目分发（完整顺序执行(有执行失败将结束本次)）的时候无法监听到项目启动失败，从而停止分发，从而导致整个集群全部停机

**Comment by bwcx-jzy** [comment]
如果是在启动过程中突然挂掉这种是没有办法直接控制到的，如果是想避免启动过程中挂掉来判断项目的启动状态需要使用 DSL 项目来自定义实现
