### ISSUE TITLE
向SSH节点（Windows11）下发文件，文件名会变为ID，而非文件名

### ISSUE THREAD

**Issue by LL-LIN** [dromara/Jpom#99]
![image](https://github.com/user-attachments/assets/e0f0694f-1d7b-407f-b138-c1f3abc07bfc)

**Comment by LL-LIN** [comment]
没仔细看文档，实际文件名称默认为下发为文件ID

**Comment by bwcx-jzy** [comment]
![851db0b1b809c5e9a87d29096474231](https://github.com/user-attachments/assets/bd5ceb2a-921d-4aa5-ba39-6f7b8cd7af1e)

**Comment by bwcx-jzy** [comment]
![image](https://github.com/user-attachments/assets/315f4ee2-c07c-46d5-a968-e1b29a941476)
